name: GitHub Snake Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create branch if it doesn't exist
      run: |
        git fetch origin
        if ! git rev-parse --verify origin/output; then
          git checkout -b output
          git push origin output
        fi

    - name: Deploy to GitHub Pages
      run: |
        git checkout output
        # Add your deployment script here
